spring:
  datasource:
    #url: jdbc:h2:file:~/h2/apph2db
    #url: jdbc:postgresql://0.0.0.0:5432/test
    url: jdbc:postgresql://0.0.0.0:5432/test
    #url: jdbc:h2:mem:testdb
    username: postgres
    password: password
    #driverClassName: org.h2.Driver
  h2:
    console:
      enabled: false
      path: /h2_console
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format:
          sql: true
    show-sql: true
  jwt:
    secret-key: "8^}S3(N}[Z&N7`v.A|3yU/ImWr!2MQV.+Ig>3:=PxndqR0I#1P=PpKiUy`wzXl%"
    token-prefix: "Bearer "
    token-expiration-after-days: 10
    authorities: authorities
