spring:
  datasource:
    #url: jdbc:h2:file:~/h2/personstatdb
    url: jdbc:h2:mem:testdb
    username: sa
    password: ''
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2_console
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format:
          sql: true
    show-sql: true
